- hosts: cs312
  tasks:
    - name: Install epel-release
      yum: name=epel-release state=present
    - name: Install httpd
      yum: name=httpd state=present
    - name: Install git
      yum: name=git state=present
    - name: Install python-pip
      yum: name=python-pip state=present
    - name: Install python-virtualenv
      yum: name=python-virtualenv state=present
    - name: Start http
      service: name=httpd state=started enabled=yes
    - name: Adding user cs312
      user: name=cs312
    - name: Cloning git repository
      git: repo=git://github.com/osuosl/cs312 dest=/var/www/html/cs312 clone=yes update=no
    - name: Run script 
      shell: /var/www/html/cs312/scripts/build.sh
      args:
          chdir: /var/www/html/cs312

